### ISSUE TITLE
Make Plugin compatible with Matomo Version 5.x  

### ISSUE THREAD

**Issue by velletti** [jbrule/matomoplugin-HidePasswordReset#4]
in my opinion, 
it is just raising the version Infos in plugin.json

downloaded current Version 

wget https://plugins.matomo.org/api/2.0/plugins/HidePasswordReset/download/4.3.3
unzip -o 4.3.3

-> changed in plugin.json Version and max riquired Matomo Version 

"version": "5.0.1",
    "theme": false,
    "require": {
        "matomo": ">=4.0.0-b1,<6.0.0-b1"
    },

php ../console plugin:activate HidePasswordReset
rm 4.3.3

and tested it sucessful in my local instance.:

-> i can configure the text in backend -> system -> general and it is showing that text.

**Comment by jbrule** [comment]
Merged. Thank you @velletti
